smtp:
  name: gh-docker-smtp-armhf
  build: .
  ports:
   - "25:25"
  environment:
    RELAY_NETWORKS: ":192.168.0.0/24:10.0.0.0/16"
    GMAIL_USER:
    GMAIL_PASSWORD:
    SES_USER:
    SES_PASSWORD:
    SES_REGION:
    RELAY_NETWORKS:
    RELAY_DOMAINS:
    KEY_PATH:
    CERTIFICATE_PATH:
    MAILNAME:
